[package]
name = "wasm-mutate"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { optional = true, version = "0.3" }
thiserror = "1.0.28"
wasmparser = { version = "0.80", path = "../wasmparser" }
wasm-encoder = { version = "0.6.0", path = "../wasm-encoder" }
wasm-smith = { version = "0.7.1", path = "../wasm-smith"}
leb128 = "0.2.4"
arbitrary = { version = "1.0.0", features = ["derive"] }



[dev-dependencies]
anyhow = "1"
wat = { version = "1", path = "../wat" }
rand = { version = "0.7.3", features = ["small_rng"] }
